### ISSUE TITLE
What if the string is long?

### ISSUE THREAD

**Issue by WhiteYin** [miguelmota/permutations#1]
`permutations('abcdefghijkl');`  
String `'abcdefghijkl'` contains 12 characters and has 12!=479001600 permutations.Run with it costs too much memory and causes the problem crash.How to avoid it in Node(v6.11.0)?

**Comment by miguelmota** [comment]
@WhiteYin yea that'll cause a problem. I don't recommend this library since it was for learning purposes. Check out [js-combinatorics](https://www.npmjs.com/package/js-combinatorics)

**Comment by WhiteYin** [comment]
@miguelmota You are right.  
Actually,there is no proper way to save all permutation results.  
I tried to use ` js-combinatorics`,but it didn't work when the array has ten more entries.
Anyway,thanks for your reply and I think this issue can be closed now.

**Comment by miguelmota** [comment]
@WhiteYin here's how you can write the results to a file

```js
var fs = require('fs')
var Combinatorics = require('js-combinatorics')

var out = fs.createWriteStream('result.csv')
var cmb = Combinatorics.permutation('abcdefghijkl'.split(''))
var x = null

while (x = cmb.next()) {
  var row = x.join(',')
  console.log(row)
  out.write(`${row}\n`)
}

out.end()
```
